# Generated by Django 3.1.2 on 2020-11-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20201109_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
