# Generated by Django 3.1.2 on 2020-11-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_auto_20201109_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
