# Generated by Django 3.1.2 on 2020-10-20 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Price in BYN'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_date',
            field=models.DateField(default=datetime.date.today, verbose_name='The date of publishing'),
        ),
    ]
