# Generated by Django 3.1.2 on 2020-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201020_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages_amount',
            field=models.IntegerField(default=0, max_length=5, verbose_name='The amount of pages'),
        ),
    ]
