# Generated by Django 3.1.2 on 2020-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Cover'),
        ),
    ]
