# Generated by Django 3.1.2 on 2020-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_limit',
            field=models.CharField(choices=[('18+', '18+'), ('16+', '16+'), ('14+', '14+'), ('12+', '12+'), ('10+', '10+'), ('8+', '8+'), ('6+', '6+'), ('3+', '3+'), ('0+', '0+')], default=1, max_length=4, verbose_name='Age limit'),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('84×108/16', '84×108/16'), ('70×90/8', '70×90/8'), ('70×90/16', '70×90/16'), ('75×90/16', '75×90/16'), ('60×90/16', '60×90/16'), ('84×108/32', '84×108/32'), ('70×90/32', '70×90/32'), ('70×108/32', '70×108/32'), ('60×90/32', '60×90/32')], default=1, max_length=15, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=True, max_length=3, verbose_name='Is active?'),
        ),
    ]
