# Generated by Django 3.1.2 on 2020-10-20 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_pages_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(default='', max_length=50, verbose_name='Binding'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_amount',
            field=models.IntegerField(default=0, verbose_name='Amount of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of publishing'),
        ),
    ]
