# Generated by Django 3.1.2 on 2020-11-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_publishinghouse'),
        ('books', '0004_auto_20201110_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='references.publishinghouse'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='references.series'),
        ),
    ]
