# Generated by Django 3.1.2 on 2020-10-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(default=0.0, verbose_name='Weight (g)'),
        ),
    ]
