# Generated by Django 3.1.2 on 2020-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], default=0, max_length=1, verbose_name='Rating'),
        ),
    ]
