# Generated by Django 3.1.2 on 2020-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20201020_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_limit',
            field=models.CharField(choices=[('1', '18+'), ('2', '16+'), ('3', '14+'), ('4', '12+'), ('5', '10+'), ('6', '8+'), ('7', '6+'), ('8', '3+'), ('6', '0+')], default=1, max_length=4, verbose_name='Age limit'),
        ),
    ]
