# Generated by Django 3.1.2 on 2020-10-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Weight (g)'),
        ),
    ]
