# Generated by Django 3.1.2 on 2020-10-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20201020_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='books_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Left amount'),
        ),
    ]
