# Generated by Django 3.1.2 on 2020-10-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_books_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of entry'),
        ),
        migrations.AddField(
            model_name='book',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of updating'),
        ),
    ]
