# Generated by Django 3.1.2 on 2020-10-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_publishinghouse'),
        ('books', '0015_auto_20201020_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre_id',
            field=models.ManyToManyField(to='references.Genre'),
        ),
    ]
