# Generated by Django 3.1.2 on 2020-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_publishinghouse'),
        ('books', '0016_book_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(to='references.Author'),
        ),
    ]
