# Generated by Django 3.1.2 on 2020-10-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_publishinghouse'),
        ('books', '0018_book_publishing_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='references.series'),
        ),
    ]
