# Generated by Django 3.1.2 on 2020-10-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_series_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='series_id',
            new_name='series',
        ),
    ]
