# Generated by Django 3.1.2 on 2020-10-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20201020_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('1', '84×108/16'), ('2', '70×90/8'), ('3', '70×90/16'), ('4', '75×90/16'), ('5', '60×90/16'), ('6', '84×108/32'), ('7', '70×90/32'), ('8', '70×108/32'), ('9', '60×90/32')], default=1, max_length=15, verbose_name='Format'),
        ),
    ]
