# Generated by Django 3.1.2 on 2020-10-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_book_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_code',
            field=models.CharField(default='', max_length=20, verbose_name='ISBN'),
        ),
    ]
