# Generated by Django 3.1.2 on 2020-10-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20201020_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(default='static/None/04blackhole1-articleLarge-v3.jpg', upload_to='static/', verbose_name='Cover'),
        ),
    ]
