# Generated by Django 3.1.2 on 2020-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20201020_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(upload_to='media/', verbose_name='Cover'),
        ),
    ]
