# Generated by Django 3.1.2 on 2020-11-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_auto_20201116_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
