# Generated by Django 3.1.2 on 2020-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_author_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of series')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='About this series')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About author'),
        ),
    ]
