# Generated by Django 3.1.2 on 2020-10-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20201018_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='About this genre')),
            ],
        ),
    ]
