# Generated by Django 3.1.2 on 2020-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=40, verbose_name='Publishing House')),
                ('history', models.TextField(blank=True, max_length=500, null=True, verbose_name='Other books of this house')),
            ],
        ),
    ]
