# Generated by Django 3.1.2 on 2020-11-22 11:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_bookincart_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.BooleanField(default=False, verbose_name='Cancel Order')),
                ('status2', models.CharField(choices=[('The order is being processed', 'The order is being processed'), ('The order is being delivered', 'The order is being delivered'), ('The order was canceled', 'The order was canceled'), ('The order is completed', 'The order is completed')], max_length=100, verbose_name='Status of order')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Delivery address')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart')),
            ],
        ),
    ]
