# Generated by Django 3.1.2 on 2020-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status2',
            field=models.CharField(choices=[('The order is being processed', 'The order is being processed'), ('The order is being delivered', 'The order is being delivered'), ('The order was canceled', 'The order was canceled'), ('The order is completed', 'The order is completed')], default='The order is being processed', max_length=100, verbose_name='Status of order'),
        ),
    ]
